### ISSUE TITLE
convert relative links to absolute

### ISSUE THREAD

**Issue by dkuku** [nabbisen/mdka-rs#35]
Hi, thanks for the project. 
Wdyt to accept an optional url param that when present would allow to convert links to absolute when a link starts with `/`

**Comment by nabbisen** [comment]
@dkuku 
Hi, thank you for the message 😊

> convert links to absolute when a link starts with /

Could I have more description about the use case ?

- "A link starts with /" seems absolute one.
- The issue title "convert relative links to absolute" seems to mean `../some/path` conversion to `/home/someone/some/path`.
- In addition, relative paths work in Markdown as well as HTML.

**Comment by dkuku** [comment]
I was thinking for example with parsed wikipedia page - the links point to other pages but I don't have it all locally.
So converting the `/wiki/article` to `https://wikipedia.org/wiki/article`
![Screenshot from 2024-06-23 12-07-09](https://github.com/nabbisen/mdka-rs/assets/904179/8e16627b-7e0b-4220-9c34-3815e177d183)

**Comment by nabbisen** [comment]
@dkuku 
Thank you for the easy-to-understand example.

It seems possible with the parameter passed to tell where you are. (In your example, the Wikipedia article URL.)
I will try to implement it as the [htmlproc-rs](https://github.com/nabbisen/htmlproc-rs)'s preprocessor function.

Besides, web scraping have possibility to solve it in more flexible way. This crate adopts text processing now, and will not possibly solve complicated situations.

**Comment by nabbisen** [comment]
https://github.com/nabbisen/htmlproc-rs/issues/7

**Comment by nabbisen** [comment]
@dkuku 
I released new feature of [htmlproc-rs](https://github.com/nabbisen/htmlproc-rs): [`path_to_url`](https://github.com/nabbisen/htmlproc-rs?tab=readme-ov-file#path_to_url).

You can preprocess your HTML before calling mdka. First, install it:

```
cargo add htmlproc --features path_to_url
```

Then:

```rust
use htmlproc::path_to_url::{convert, ConvertOptions};

let result: String = convert("<a href=\"/some/path\">link</a>", ConvertOptions::new("target.domain"));
```

**Comment by dkuku** [comment]
cool, thanks. I will ad this to https://github.com/dkuku/mdka_ex/

**Comment by nabbisen** [comment]
@dkuku 
Wow, pretty nice project on Elixir !!
