### ISSUE TITLE
IDs syntax in Markdown differs from current implementation

### ISSUE THREAD

**Issue by getreu** [nabbisen/mdka-rs#43]
Consider: 
`# text { #id .class1 .class2 myattr other_attr=myvalue }` is interpreted as a level 1 heading with the content text, ID id, classes class1 and class2 and custom attributes myattr (without value) and other_attr with value myvalue. Note that ID, classes, and custom attributes should be space-separated.

See: [HEADING_ATTRIBUTES](https://docs.rs/pulldown-cmark/0.11.0/pulldown_cmark/struct.Options.html#associatedconstant.ENABLE_HEADING_ATTRIBUTES)

**Comment by nabbisen** [comment]
The extension format is not standardized. For example, VS Code Markdown preview can't draw it. It is therefore not supported by this crate.

**Comment by getreu** [comment]
> The extension format is not standardized.  For example, VS Code Markdown preview can't draw it.

VS Code Markdown renders Github-flavoured  Markdown, which is [CommonMark](https://commonmark.org/) compliant with some Github extensions.

When it comes to extensions there is no formal specification. The quasi widely accepted standard is defined here: [Pandoc - Extensions](https://pandoc.org/MANUAL.html#extensions)
